//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svendeproeve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public Collection()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int CollectionID { get; set; }
        public string CollectionName { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
