//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svendeproeve.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sv_Eksamen_Entities : DbContext
    {
        public Sv_Eksamen_Entities()
            : base("name=Sv_Eksamen_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collection> Collection { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Newsletter> Newsletter { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Retailer> Retailer { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Userlogin> Userlogin { get; set; }
    }
}
