//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svendeproeve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<int> RetailerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> CollectionID { get; set; }
    
        public virtual Collection Collection { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Retailer Retailer { get; set; }
        public virtual Userlogin Userlogin { get; set; }
    }
}
