//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svendeproeve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public Retailer()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int RetailerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Zipcode { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Image { get; set; }
        public string Logo { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
