//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svendeproeve.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userlogin
    {
        public Userlogin()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string LoginName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual Role Role { get; set; }
    }
}
